# Generated by Django 3.2.8 on 2021-11-16 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performer', models.CharField(max_length=255, verbose_name='Исполнители')),
                ('amount', models.IntegerField(verbose_name='Количество билетов')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость билета')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('address', models.CharField(max_length=150, verbose_name='Место проведения')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('map', models.TextField(blank=True, verbose_name='Местоположение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket.event')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('composer', models.CharField(max_length=150, verbose_name='Композитор')),
                ('voicetype', models.CharField(blank=True, max_length=100, verbose_name='Тональность исполнителя')),
            ],
            bases=('ticket.event',),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket.event')),
                ('constraint', models.IntegerField(verbose_name='Возрастное ограничение')),
            ],
            bases=('ticket.event',),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket.event')),
                ('headliner', models.CharField(max_length=255, verbose_name='Хедлайнер')),
                ('route', models.TextField(verbose_name='Как добраться')),
            ],
            bases=('ticket.event',),
        ),
    ]
