# Generated by Django 3.2.8 on 2021-11-16 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator('0')], verbose_name='Количество билетов'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator('0.00')], verbose_name='Стоимость билета'),
        ),
        migrations.AlterField(
            model_name='party',
            name='constraint',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator('0.00')], verbose_name='Возрастное ограничение'),
        ),
    ]
